debois/elm-mdl

- elm-package.json
- examples/Demo.elm
- examples/Routing.elm
Hi @debois, 
I added the sporto/hop router to the demo module to address #7.
With this addition the tabs are activated by visiting the url (example `http://localhost:8000/#grid`) or by clicking the tab in the UI. When the tab is clicked in the UI, the path is also updated. 
Currently the routes are hardcoded in the `changeTab` function and also in `Routing.matchers`. A bit ugly, but perhaps it's sufficient for the demo. What do you think?
> Add Hop router to Demo Example.

- demo/Demo.elm
- src/Material/Layout.elm
Current implementation of Transparency is not exclusive with other header modes.
Not sure whether to add a Transparent mode and have it be exclusive with the other modes or if being able to have for example a transparent scrolling header is intended. 
Also currently the example is using the background from the getmdl.io transparency example.
> Add Transparent Header option to Layout

- src/Material/Footer.elm
Dropdown section was missing a input checkbox element to handle automatic resize on small screens.
> Fix dropdown section not handling small screens

- demo/Demo.elm
- demo/Demo/Slider.elm
- elm-package.json
- src/Material.elm
- src/Material/Slider.elm
Initial implementation of a `Slider` component to resolve #69.
Did a major refactor of the API based on the [discussion](https://github.com/debois/elm-mdl/issues/69).
The component does not currently use or support `Parts` component model because the component itself has no need for `update` because of the user having to provide both `onChange` and `value` calls to update the slider.
`Slider` does not currently work properly on [Microsoft Edge](https://github.com/google/material-design-lite/issues/1625). It also does not currently look the best on regular Internet Explorer due to flexbox. However, it is functional.
Example use: 
```elm 
import Material.Slider as Slider
slider : Model -> Html Msg
slider model =
p [ style [ ("width", "300px") ] ]
[ Slider.slider
[ Slider.onChange SliderMsg …
```
> Initial implementation of Slider Component 

- examples/Component.elm
* The `Platform` import is superfluous.
* The Msg constructor was given in wrong capitalization.
Still, though: The item
> An initial model (`(Button.model True)`---a button with a ripple animation.
is confusing, since nothing like `(Button.model True)` acually occurs in the file.
> Improve example documentation

- demo/Demo.elm
- demo/Demo/Typography.elm
- elm-package.json
- src/Material/Typography.elm
Initial implementation of `Typography` module to resolve #18.
Right now it simply returns the class strings, that the user must manually apply to with a `Html.class`. 
Example use: 
```elm 
import Material.Typography as Typo
import Html exposing (p)
import Html.Attributes exposing (class)
example : Html msg 
example = p [ class Typo.display4 ] 
[text "Light 112px"]
```
There is also an utility to combine many classes
```elm
import Material.Typography as Typo
import Html exposing (p)
example : Html msg 
example = p [ Typo.many [Typo.left, Typo.titleColorContrast] ] 
[ text "Left align" ]
```  
I wish `Html.class` would work like `Material.Options.cs` allowing you to have multiple `class` declarations in your properties. This would allow for simpler API.  
Open to feedback and suggestions.
> Typography

- demo/Demo/Textfields.elm
- src/Material/Textfield.elm
Had some time on my hands so added some attributes that were discussed in #87.
```elm
, Textfield.render MDL [6] model.mdl
[ Textfield.label "Default multiline textfield (50 char limit)"
, Textfield.textarea
, Textfield.autofocus -- New 
, Textfield.maxlength 50 -- New
, Textfield.onBlur (Blur [6]) -- New
, Textfield.onFocus (Focus [6]) -- New
]
```
> Textfield extra attributes

- src/Material/Button.elm
IE11 Does not support creating Synthetic Events using `new Event`.
Temporary workaround using deprecated `document.createEvent`.
Tested on newest Firefox, Chrome, IE11 and Edge.
> Temporary fix for #114

- demo/Demo.elm
For some reason `toggleDrawer` toggles the scroll bar. Resolves #136
> Temporary fix for #136

- src/Material/Button.elm
- src/Material/Card.elm
- src/Material/Dialog.elm
- src/Material/Elevation.elm
- src/Material/Footer.elm
- src/Material/Grid.elm
- src/Material/Layout.elm
- src/Material/List.elm
- src/Material/Menu.elm
- src/Material/Progress.elm
- src/Material/Slider.elm
- src/Material/Snackbar.elm
- src/Material/Spinner.elm
- src/Material/Table.elm
- src/Material/Tabs.elm
- src/Material/Template.elm
- src/Material/Textfield.elm
- src/Material/Toggles.elm
- src/Material/Tooltip.elm
- src/Material/Typography.elm
Apparently it was not just the one that I fixed, but *all* of them were broken because the template was wrong.  Fixed them all, fixed the template, tested every-single-one, think I got them all.
Also, there is a lot of inconsistency in the Demo naming.  Some demo's are the same name as the type like Snackbar, Dialog, Grid, and more even though they show multiples, and others are like Footer/Footers, Card/Cards, etc...  Should probably be unified, I'd say to the same name as the type to make lookup and links easier.
For now, url fixes here, template too.
> Extra url fixes

- demo/Demo/Textfields.elm
- src/Material/Textfield.elm
Resolves #130  
This also refactors the way event handlers are used internally.
Instead of adding the internal handlers on the input element.
The handlers are now added to the containing div using events that
are known to bubble (`input`, `focusin`, `focusout`)
See the demo code for an example for `keyup` event
The user event handlers are now added to the input element.
Open to feedback and suggestions on this one.
> Add support for custom event handlers on Textfield

- demo/Demo/Textfields.elm
> Docs: Textfield demo is now consistent with rest of the components

- README.md
- REFERENCE_IMPLEMENTATIONS.md
- src/Material/Layout.elm
This is the initial list I've found just by searching. We may need some kind of quality check to see if these are valid implementations. Not sure if we should call this reference implementations or something else. I added a link from the main readme.
Note - I recently set my editor to remove trailing whitespaces - that seems to be the reason why there are so many lines are changed in the readme.md file. I can revert this if this is a problem.
> Reference implementations

- demo/Demo/Textfields.elm
- src/Material/Textfield.elm
This will resolve #166 temporarily but it will also break #87 `onBlur` and `onFocus` custom handlers
on Firefox.
Firefox does not support `focusin` and `focusout` events currently.
> Temporary fix for #166

- src/Material/Button.elm
I hope this helps. My editor seems to have stripped all trailing space from lines. The real edit is the addition of a libe break at 378 to ensure the example renders properly when turned into documentation
> add space to ensure proper rendering of documentation for render

- src/Material/Button.elm
This allows for setting the type of the button.
```elm
Button.render ...
[ Button.type' "button"
]
[ ... ]
```
> Add support for type' for Buttons.

- src/Material/Options.elm
- src/Material/Slider.elm
- src/Material/Textfield.elm
- src/Material/Toggles.elm
Resolves #204
`Options.id` allows users to specify the `id` that can then be
used with the new DOM API.
`Options.inner` allows users to specify attributes on `inner`
elements of components that support it.
I went through the list by @debois in #204. Only components that I really found needing support for `Options.inner` were `Textfield` as well as `Toggles`, both of them have `input` elements that the users can now add attributes to with `Options.inner`. 
Most of the other components have users specify sections of content already and for those they can just use `Options.id` (such as Tabs and Grids). For other components there was really no clear `inner` element that would benefit from enabling this support.
As always looking for feedback and suggestions, especially if there is a component …
> Add support for id and inner attributes

- README.md
I agree with my previous contributions licensed under BSD3 now being contributions under Apache v2.
BSD3: https://opensource.org/licenses/BSD-3-Clause
Apache v2: https://www.apache.org/licenses/LICENSE-2.0
> LICENSE UPDATE

- USERS.md
Accidentally noticed that my project is in USERS.md. I was confused why I was getting traffic on it all of a sudden :)
Here's a correct description for my project - the previous one was leftover from a starter kit I forked. Wouldn't want people to come there thinking it's a webpack boilerplate :) (that would be https://github.com/moarwick/elm-webpack-starter, which is awesome)
> Correct project description in USERS.md

- .travis.yml
- TESTING.md
- USERS.md
- tests/.gitignore
- tests/Main.elm
- tests/Tests.elm
- tests/elm-package.json
This adds a separate tests folder to elm-mdl. This does not affect elm-mdl in any way. I've also update the travis.yml file to use caching (reduces build time from 43 to 17 minutes) and use the test framework.
The current Travis CI build speed is 40-50 minutes. A couple of weeks ago, I tested the caching described in this [article](https://8thlight.com/blog/rob-looby/2016/04/07/caching-elm-builds-on-travis-ci.html), but with no luck. 
All other examples used [elm-test](https://github.com/elm-community/elm-test) as the last step in Travis CI, so I've implemented some basic tests using [elm-test](https://github.com/elm-community/elm-test). The Travis CI build is now down to 17 minutes - it's possible that it can be reduced more by caching the entire "elm-stuff" folder.
One primary reason I …
> Elm-test framework and Travis CI speed improvements

- demo/Demo/Textfields.elm
- src/Material/Textfield.elm
Initial support to resolve #198.  
Currently requires user to provide ID for the element as a parameter to `Textfield.expandable` for example `Textfield.expandable "expandable-textfield-id"`. This allows the implementation to stay extremely simple and not require any sort of JavaScript or other hacks to achieve the necessary functionality.
> Add support for expandable textfields

- src/Material/Card.elm
- src/Material/Footer.elm
- src/Material/Layout.elm
- src/Material/Menu.elm
- src/Material/Options.elm
- src/Material/Options/Internal.elm
This is a initial implementation of generic attribute support
to enable arbitrary `Html.Attributes` to resolve #208 . This implementation
tries to minimize the likelihood of overriding internally used
attributes while still maintaining `MINOR` change.
This implementation may be revisited in the next MAJOR version
to update the implementation.
Add namespaced qualifiers to `Internal.attribute`,
this way internal attributes are easy to search for as well separate
them from `Options.attribute`.
As always, open to feed back and suggestions!
> Initial implementation of generic attribute support

- README.md
Changes links for FAQ.md and USERS.md
According to issue #214, elm-package currently does not like relative links in README. I've updated to fixed links - pointing to v7 branch. I noticed that the link to CONTRIBUTING.md was pointing to master.
> Change links from fixed to relative

- demo/Demo/Dialog.elm
- demo/Demo/Elevation.elm
- demo/Demo/Loading.elm
- demo/Demo/Tables.elm
- demo/Demo/Toggles.elm
Updates all of the outdated link references in the Demo.
- [Material Design Component Dialogs](https://material.google.com/components/dialogs.html)
- [Material Design Component Loading](https://material.google.com/components/progress-activity.html)
- [Material Design Lite Elevation/Shadow](https://github.com/google/material-design-lite/blob/mdl-1.x/src/shadow/README.mdl)
- [Material Design Lite Loading](https://getmdl.io/components/index.html#loading-section)
- [Material Design Lite Tables](https://getmdl.io/components/index.html#tables-section)
- [Material Design Lite Toggles](https://getmdl.io/components/index.html#toggles-section)
> Update broken Demo link references

- build_scripts/hooks/commit-msg
- build_scripts/install_hooks.sh
As discussed earlier on guiding us into making correct commit messages.
I've modified the script [here](http://stackoverflow.com/questions/21641085/how-do-i-enforce-the-50-character-commit-summary-line-in-sublime)
I've changed the implementation to only gently warn when not making a correct commit message.
This is the result from a message that break all the rules:
`
> Git commit message warnings:
> These are guidelines to help us improve commit messages.
> Warning - line 1: Please limit the subject line to 50 characters.in length.
> Warning - line 1: Please capitalize the subject line.
> Warning - line 1: Please do not end the subject line with a period.
> Warning - line 2: Please separate subject from body with a blank line.
> Warning - line 4: Please wrap the body at 72 characters.
> …
> Add a commit hook to warn on incorrect commit message

- tests/Main.elm
- tests/Tests.elm
- tests/elm-package.json
Elm-test packages updated to current versions. They also needs to be in sync with root elm-package to work correctly. Seems to work ok with travis on my fork.
> V8 upgrade and fix elm test

- .travis.yml
- build_scripts/check_pr_branch.sh
If we're submitting a PR against master:
- PATCH, MINOR —> reject
- MAJOR —> accept
If we're submitting a PR against something not master:
- PATCH, MINOR —> accept
- MAJOR —> reject
I've only tested this  locally without Travis CI
We could still enhance the script to avoid hardcoded names for branch v7 / v8, version 7.0.0.0 etc.
> Add Travis CI script to enforce correct PR branch
