demo/Demo/Textfields.elm, src/Material/Textfield.elm
Adds support for multi-line textfields using textareas to address #30 
Not 100% sure on using a string type' comparison to detect type for a textarea.
=> Add support for multi-line textfields (textareas)

demo/Demo.elm, demo/Demo/Loading.elm
Update the loading demo to use a grid and add some 'interactive' demos that show a progress bar that updates and a spinner that shows while the update is in progress
=> Loading demo update

src/Material/Menu.elm
=> Allow Change of Menu Icon (#61)

demo/Demo/Tabs.elm, src/Material/Tabs.elm
A simple fix to reset scrolling when switching between tabs.
=> Use a keyed node to reset scroll when switching tabs

src/Material/Toggles.elm
=> Set default value for ripple to false

src/Material/Scheme.elm
... so that it will be properly highlighted on the package site.
=> Fix indenting in code example

demo/Demo/Textfields.elm
Add samples for each of the `Textfield` examples to resolve #101 
The Textfield example layout could possibly use some tuning with the samples.
=> Add code samples for Textfields

demo/Demo/Footer.elm
Add code samples for both styles of footers to resolve #97
=> Add code samples for Footers

demo/Demo.elm, demo/Demo/Card.elm, demo/Demo/Cards.elm, src/Material/Card.elm
This is my proposal for the Card component. I've included a demo page. There seems to be a styling issue with subtitles, however I can replicate the odd styling by inserting a subtitle using the inspector on https://getmdl.io/components/index.html#cards-section.
=> Card component

demo/Demo/Elevation.elm
Add some basic sample code for the `Elevation` examples to resolve #96
=> Add code samples for Elevation examples

demo/Demo.elm, demo/Demo/Dialog.elm, src/Material/Dialog.elm
=> Add Dialog Component

demo/Demo/Tables.elm, src/Material/Table.elm
=> Update tables demo with controls

demo/Demo/Menus.elm, src/Material/Menu.elm
Warning: Select handler currently broken!
=> Change menu API, implement keyboard input

src/Material/Icon.elm
=> Docs: Typo in Icon.elm

CONTRIBUTING.md, demo/Demo/Layout.elm, demo/page.html, src/Material/Layout.elm, src/Material/Scheme.elm
Version 1.2.0 fixes some issues and adds support for new component `Chip`.
Resolves #187
=> Update MDL to version 1.2.0

demo/Demo.elm, demo/Demo/Chips.elm, elm-package.json, src/Material/Chip.elm, src/Material/Options.elm
Initial implementation of the `Chip` component new in version 1.2.0 to resolve #128 
Demo could use some beefing up perhaps.
=> Initial implementation Chip component

FAQ.md, README.md
I've just added some structure and text. I have not filled out all answers or linked this file from the readme.
=> Initial FAQ template

LICENSE.md, demo/elm-package.json, elm-package.json, src/Material/Layout.elm
LICENSE UPDATE
I agree with my previous contributions licensed under BSD3 now being contributions under Apache v2.
BSD3: https://opensource.org/licenses/BSD-3-Clause
Apache v2: https://www.apache.org/licenses/LICENSE-2.0
=> Licence acceptance

USERS.md
Followed GitHub merge PR command line instructions and this created a separate PR. I'' create this PR and reference #197
=> Add reference implementation and repository for Offtie.com

src/Material/Layout.elm
=> type alias, not type

demo/Demo/Cards.elm
Broken reference to Cards.elm example source code fixed.
=> #256 broken source code link fixed

demo/Demo/Buttons.elm, src/Material/Button.elm
This resolves #201. The implementation was simplified in a large way
with #213.
=> Initial implementation of Link buttons
